site_name: Adventures

nav:
  - Phandelver:
      - In Neverwinter: phandelver-00.md
      - Day 1: phandelver-01.md
      - Day 2: phandelver-02.md

theme:
  name: material
  palette:
    primary: indigo
    accent: red
    hue:
      - '300'
      - '500'
    bg: 'white'
  logo: 'material/library'
  favicon: 'material/library'
