site_name: My Adventures
site_url: https://jonasmcferreira.github.io/adventures/

nav:
  - Phandelven:
      - In Neverwinter: phandelven/00.md
      - Day 1: phandelven/01.md
      - Day 2: phandelven/02.md

theme:
  name: material
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    logo: material/library
  favicon: 'material/library'
  font:
    text: Lora
  features:
    - navigation.footer
    - navigation.path
    - navigation.top
    - navigation.tabs

plugins: []

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
