site_name: Adventures
site_url: https://jonasmcferreira.github.io/adventures/

nav:
  - Phandelver:
      - In Neverwinter: phandelver/00.md
      - Day 1: phandelver/01.md
      - Day 2: phandelver/02.md

theme:
  name: material
  palette:
    primary: indigo
    accent: red
    hue:
      - '300'
      - '500'
    bg: 'white'
  logo: 'material/library'
  favicon: 'material/library'

  # Add these lines to reference the font files
  extra_css:
    - 'fonts/EBGaramond-Regular.ttf'
    - 'fonts/EBGaramond-Bold.ttf'
    - |
      @font-face {
        font-family: 'EB Garamond';
        font-style: normal;
        font-weight: 400;
        src: url('fonts/EBGaramond-Regular.ttf') format('truetype');
      }
      @font-face {
        font-family: 'EB Garamond';
        font-style: normal;
        font-weight: 700;
        src: url('fonts/EBGaramond-Bold.ttf') format('truetype');
      }


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
