site_name: My Adventures
site_url: https://jonasmcferreira.github.io/adventures/

nav:
  - Phandelver:
    - Characters: phandelver/characters.md
    - Day 0: phandelver/00.md
    - Day 1: phandelver/01.md
    - Day 2: phandelver/02.md
    - Day 3: phandelver/03.md
    - Day 4: phandelver/04.md
    - Day 5: phandelver/05.md
    - Day 6: phandelver/06.md

theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: red
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: red
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    logo: material/sword-cross
  favicon: 'material/library'
  font:
    text: Lora
  features:
    - navigation.footer
    - navigation.path
    - navigation.top
    - navigation.tabs

plugins: 
  - glightbox

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
