site_name: Adventures

nav:
    - Phandelver: 
      - In Neverwinter: phandelver-00.md
      - Day 1: phandelver-01.md
      - Day 2: phandelver-02.md

    
    

theme:
  name: material
  palette:
    primary: indigo
    accent: red
    hue:
      - '300'
      - '500'
    bg: 'white'
  logo: 'material/library'
  favicon: 'material/library'

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/jonasmcferreira
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jonasferreira/

copyright: code is love

extra_css:
  - stylesheets/extra.css

plugins: []

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
